version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - ${DOCKER_HOST_PORT:-81}:${APP_PORT:-80}
    volumes:
      - ./:/yoku/api
    env_file: 
      - ./.env
    depends_on:
      - postgres
    networks:
      - yoku
    restart: always

  postgres:
    image: postgres:15.1
    ports:
      - ${DOCKER_DB_PORT:-5433}:${POSTGRES_PORT:-5432}
    env_file: 
      - ./.env
    volumes:
      - /yoku/postgres:/var/lib/postgresql/data
    networks:
      - yoku
    restart: always

  dashboard:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - ${DOCKER_NODE_PORT:-82}:5173
    volumes:
      - ./web:/yoku/dashboard
    command: npm run dev
    depends_on:
      - api
    networks:
      - yoku
    restart: always
networks:
  yoku:
